export const GOGGLESCONST = {
    GET_WEBSITE_LIST: 'GET_WEBSITE_LIST_GOGGLESCONST',
    NAVIGATE_TO_OUTSIDE: 'NAVIGATE_TO_OUTSIDE_GOGGLESCONST',
};

export const USERCONST = {
    SET_USER_DETAILS: 'SET_USER_DETAILS_USERCONST',
    GET_USER_DETAILS: 'GET_USER_DETAILS_USERCONST',
}

export default GOGGLESCONST