export const GOGGLESCONST = {
    GET_WEBSITE_LIST: 'GET_WEBSITE_LIST_GOGGLESCONST',
};

export const USERCONST = {
    SET_USER_DETAILS: 'SET_USER_DETAILS_USERCONST',
    GET_USER_DETAILS: 'GET_USER_DETAILS_USERCONST',
}